title: "PicMe Gallery"
description: "This is an app that helps you get and share great-looking
photos of you and your friends. This is the only app you'll even need to pick from the Google Play Store."
author:
  name: "Shayan Golafshani, ALex Garber, and Isaac Dominguez"

theme: jekyll-theme-slate